job_board/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),   
    path('', include('user.urls')), 
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.contrib import admin

app_name = 'user'
#from .views import register_candidate, CandidateLoginView

urlpatterns = [
    path('', views.home, name= 'home'),
    path('home/', views.home, name= 'home'),
    path('login/', views.login_user, name='login'), 

    path('logout/', views.logout_user, name= 'logout'),
    path('job_listing/', views.job_listing, name= 'job_listing'),
    path('about/', views.about, name= 'about'),
    path('contact/', views.contact, name= 'contact'),
    path('job_details/<int:myid>/', views.job_details, name= 'job_details'),
    path('employers/', views.employers, name= 'employers'),
    path('candidates/', views.candidates, name= 'candidates'),
    
    path('candidate_details/<int:myid>', views.candidate_details, name= 'candidate_details'),

    path('search/', views.search_results, name= 'search_results'),
    
    #admin
    path('settings/', views.settings, name= 'settings'),
    path('delete_account/', views.delete_account, name='delete_account'), 


    # User
    path('user_homepage/', views.user_homepage, name= 'user_homepage'),  
    path('register_candidates/', views.register_candidates, name= 'register_candidates'),  
    path('user_profile/', views.user_profile, name= 'user_profile'),
    path('job_apply/<int:myid>/', views.job_apply, name= 'job_apply'),
    path("applied_jobs/", views.applied_jobs, name="applied_jobs"),
    path('delete_applied_job/<int:application_id>/', views.delete_applied_job, name='delete_applied_job'),
    
    path("notification/", views.notification, name="notification"),


    # Company
    path('company_homepage/', views.company_homepage, name= 'company_homepage'),  

    path('register_company/', views.register_company, name= 'register_company'),  
    path('company_homepage/', views.company_homepage, name= 'company_homepage'),  
    path('company_profile/', views.company_profile, name= 'company_profile'),  
    path('add_job/', views.add_job, name= 'add_job'),  
    path('job_list/', views.job_list, name= 'job_list'),  
    path('edit_job/<int:myid>/', views.edit_job, name= 'edit_job'),  
    path('delete-job/<int:job_id>/', views.delete_job, name='delete_job'),

    path('job/delete/<int:job_id>/', views.delete_job, name='delete_job'),

    path('job_detail/<int:myid>/', views.job_detail, name= 'job_detail'),  

    path('all_applicants/', views.all_applicants, name= 'all_applicants'),  
    path('delete-applicant/<int:id>/', views.delete_applicant, name='delete_applicant'),


    path('company/<int:company_id>/vacancies/', views.company_vacancies, name='company_vacancies'),
   
    path('download',views.all_download,name='download'),
    path('forgot/', views.forgot_password, name='forgot_password'),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='accounts/forgot.html'), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'), name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'), name='password_reset_complete'),
 ]

templates/admin_header.html
{% if user.is_authenticated %}
{% include 'admin_header.html' %}
{% endif %}




{% load static %}

<nav class="navbar navbar-expand-lg bg-color-nav rounded shadow-sm  navbar-dark" aria-label="Main navigation">
  <div class="container-fluid">
    <a class="navbar-brand" href="#"> {% if user.is_authenticated %}

      Hello, <b>{{ user.username}}</b>
      {% else %}
      {% endif %}</a>
    <button class="navbar-toggler p-0 border-0" type="button" id="navbarSideCollapse" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="navbar-collapse offcanvas-collapse" id="navbarsExampleDefault">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
 
 
        {% if user.is_authenticated %}
        <!-- Check if the user is an Applicant -->
        {% if is_applicant %}
            <li class="nav-item">
                <a class="nav-link {% if request.path == '/user_homepage/' %}active{% endif %}" href="{% url 'user:user_homepage' %}">Dashboard</a>
            </li>
            <li class="nav-item">
                <a class="nav-link {% if request.path == '/user_profile/' %}active{% endif %}" href="{% url 'user:user_profile' %}">Profile</a>
            </li>
        <!-- Check if the user is a Company -->
        {% elif is_company %}
            <li class="nav-item">
                <a class="nav-link {% if request.path == '/company_homepage/' %}active{% endif %}" href="{% url 'user:company_homepage' %}"> Dashboard</a>
            </li>
            <li class="nav-item">
                <a class="nav-link {% if request.path == '/company_profile/' %}active{% endif %}" href="{% url 'user:company_profile' %}"> Profile</a>
            </li>
        {% endif %}
    {% endif %}
        <li class="nav-item">
          <a class="nav-link" href="#">Notifications</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown" aria-expanded="false">Settings</a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-light" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

templates/company_vacancies.html
{% extends 'base.html' %}
{% block title %} Job Listing Page {% endblock %}
{% block content %}
{% load static %}
    <div class="slider-area ">
      <div class="single-slider section-overly slider-height2 d-flex align-items-center"
        data-background="/static/img/about.jpg" style="background-image: url(&quot;/static/img/about.jpg&quot;);">
        <div class="container">
          <div class="row">
            <div class="col-xl-12">
              <div class="hero-cap text-center">
                <h2>Job Vacancies at <em><u>{{ company.company_name }}</u> </em></h2>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>



    <div class="clearfix"></div>
    <div class="job-listing-area pt-120 pb-120">
      <div class="container">
        <div class="row"> 
          <div class="col-xl-3 col-lg-3 col-md-4">
            <div class="row">
              <div class="col-12">
                <div class="small-section-tittle2 mb-45">
                  <div class="ion"> <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
                      width="20px" height="12px">
                      <path fill-rule="evenodd" fill="rgb(27, 207, 107)"
                        d="M7.778,12.000 L12.222,12.000 L12.222,10.000 L7.778,10.000 L7.778,12.000 ZM-0.000,-0.000 L-0.000,2.000 L20.000,2.000 L20.000,-0.000 L-0.000,-0.000 ZM3.333,7.000 L16.667,7.000 L16.667,5.000 L3.333,5.000 L3.333,7.000 Z">
                      </path>
                    </svg>
                  </div>
                  <h4>Filter Jobs</h4>
                </div>
              </div>
            </div> 
            <div class="job-category-listing mb-50"> 
              <div class="single-listing">
                <div class="small-section-tittle2">
                  <h4>Job Category</h4>
                </div> 
                <div class="select-job-items2">
                  <select name="select">
                    <option value="">All Category</option>
                    <option value="">Category 1</option>
                    <option value="">Category 2</option>
                    <option value="">Category 3</option>
                    <option value="">Category 4</option>
                  </select>
              
                </div> 
                <div class="select-Categories pt-80 pb-50">
                  <div class="small-section-tittle2">
                    <h4>Job Type</h4>
                  </div>

                  <div class="form-check">
                    <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
                    <label class="form-check-label" for="flexCheckDefault">
                      Full Time
                    </label>
                  </div>
                  <div class="form-check">
                    <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
                    <label class="form-check-label" for="flexCheckDefault">
                      Part Time
                    </label>
                  </div>
                  <div class="form-check">
                    <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
                    <label class="form-check-label" for="flexCheckDefault">
                      Remote
                    </label>
                  </div>
                  <div class="form-check">
                    <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
                    <label class="form-check-label" for="flexCheckDefault">
                      Freelance
                    </label>
                  </div>




                </div> 
              </div> 
              <div class="single-listing">
                <div class="small-section-tittle2">
                  <h4>Job Location</h4>
                </div> 
                <div class="select-job-items2">
                  <select name="select">
                    <option value="">Anywhere</option>
                    <option value="">Category 1</option>
                    <option value="">Category 2</option>
                    <option value="">Category 3</option>
                    <option value="">Category 4</option>
                  </select>
           
                </div> 
                <div class="select-Categories pt-80 pb-50">
                  <div class="small-section-tittle2">
                    <h4>Experience</h4>
                  </div>

                  <div class="form-check">
                    <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
                    <label class="form-check-label" for="flexCheckDefault">
                      1-2 Years
                    </label>
                  </div>
                  <div class="form-check">
                    <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
                    <label class="form-check-label" for="flexCheckDefault">
                      2-3 Years
                    </label>
                  </div>
                  <div class="form-check">
                    <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
                    <label class="form-check-label" for="flexCheckDefault">
                      3-6 Years
                    </label>
                  </div>
                  <div class="form-check">
                    <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
                    <label class="form-check-label" for="flexCheckDefault">
                      6-more..
                    </label>
                  </div>



 
                </div> 
              </div> 
              <div class="single-listing"> 
                <div class="select-Categories pb-50">
                  <div class="small-section-tittle2">
                    <h4>Posted Within</h4>
                  </div>




                  <div class="form-check">
                    <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
                    <label class="form-check-label" for="flexCheckDefault">
                      Any
                    </label>
                  </div>
                  <div class="form-check">
                    <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
                    <label class="form-check-label" for="flexCheckDefault">
                      Today
                    </label>
                  </div>
                  <div class="form-check">
                    <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
                    <label class="form-check-label" for="flexCheckDefault">
                      Last 2 days
                    </label>
                  </div>
                  <div class="form-check">
                    <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
                    <label class="form-check-label" for="flexCheckDefault">
                      Last 3 days
                    </label>
                  </div>
                  <div class="form-check">
                    <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
                    <label class="form-check-label" for="flexCheckDefault">
                      Last 5 days
                    </label>
                  </div>

                  <div class="form-check">
                    <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
                    <label class="form-check-label" for="flexCheckDefault">
                      Last 10 days
                    </label>
                  </div>

       


               
                </div> 
              </div>
             
            </div> 
          </div> 
          <div class="col-xl-9 col-lg-9 col-md-8"> 
            <section class="featured-job-area">
              <div class="container"> 
                <div class="row">
                  <div class="col-lg-12">
                    <div class="count-job mb-35">
                      <span>39, 782 Jobs found</span> 
                      <div class="select-job-items">
                        <span>Sort by</span>
                        <select name="select" >
                          <option value="">None</option>
                          <option value="">job list</option>
                          <option value="">job list</option>
                          <option value="">job list</option>
                        </select>
                   
                      </div> 
                    </div>
                  </div>
                </div> 

                <div class="container">
         
                    
                    {% if jobs %}
                    {% for job in jobs %}
                    <!-- single-job-content -->
                    <div class="single-job-items mb-30">
                      <div class="job-items">
                        <div class="company-img">
                       
                          <a href="/job_details/{{ job.id }}/">

                           {% if job.image %}
                           <img src="{{job.image.url}}" alt="">
                           {% else %} 
                          <img src="/static/img/user.png" alt="Image" > 
                           {% endif %}
                            
                           
                          
                          </a>
                        </div>
                        <div class="job-tittle job-tittle2">
                          <a href="/job_details/{{ job.id }}/">
                            <h4>{{ job.title }}</h4>
                          </a>
                          <ul>
                            <li>{{job.company.company_name}}</li>
                            <li><i class="fas fa-map-marker-alt"></i>{{job.location}}</li>
                            <li>₹{{job.salary}}/month</li>
                          </ul>
                        </div>
                      </div>
                      <div class="items-link items-link2 f-right">
                        <a href="/job_details/{{ job.id }}/">{{job.job_type}}</a>
                        <span>{{job.creation_date}}</span>
                      </div>
                    </div>
                    <!-- single-job-content -->
                    {% endfor %}
                    {% else %}
                    <p>No job vacancies available at {{ company.company_name }} at the moment.</p>
                {% endif %}



                     
                    <a href="{% url 'user:employers' %}">Back to Companies</a>   
                </div>
           
            
             
              </div>
        
            </section>
            <nav aria-label="Page navigation example">
              <ul class="pagination justify-content-center">
                
             
            
              </ul>
            </nav>
            
            
          </div>
        </div>
      </div>
    </div>
    {% endblock %}

templates/delete_account_confirm.html
{% extends 'base.html' %}
{% block title %} Contact Page {% endblock %}
{% block content %}
{% load static %}




<div class="clearfix"></div>




<section class="contact">

    <div class="container-fluid">


        <div class="row">

            {% include 'admin_sidemenu.html' %}

            <div class="col-md-10 bg_color">
                <div class="home_content_area">

                    <h2>Are you sure you want to delete your account?</h2>
                    <p>This action cannot be undone.</p>

                    <form method="POST" action="{% url 'user:delete_account' %}">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger">Yes, Delete My Account</button>
                        <br>
                        <a href="{% url 'user:login' %}" class="mt-4 p-3">No, Go Back</a>
                    </form>


                </div>


            </div>

        </div>
    </div>
</section>




{% endblock %}

templates/employers.html
{% extends 'base.html' %}
{% block title %} Job Listing Page {% endblock %}
{% block content %}
{% load static %}
<div class="slider-area ">
  <div class="single-slider section-overly slider-height2 d-flex align-items-center"
    data-background="/static/img/about.jpg" style="background-image: url(&quot;/static/img/about.jpg&quot;);">
    <div class="container">
      <div class="row">
        <div class="col-xl-12">
          <div class="hero-cap text-center">
            <h2>Employers</h2>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>



<div class="clearfix"></div>
<div class="job-listing-area pt-120 pb-120">
  <div class="container">
    <div class="row">
      <!-- Left content -->
      <div class="col-xl-3 col-lg-3 col-md-4 filter">
        <div class="row">
          <div class="col-12">
            <div class="small-section-tittle2 mb-45">
              <div class="ion"> <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
                  width="20px" height="12px">
                  <path fill-rule="evenodd" fill="rgb(27, 207, 107)"
                    d="M7.778,12.000 L12.222,12.000 L12.222,10.000 L7.778,10.000 L7.778,12.000 ZM-0.000,-0.000 L-0.000,2.000 L20.000,2.000 L20.000,-0.000 L-0.000,-0.000 ZM3.333,7.000 L16.667,7.000 L16.667,5.000 L3.333,5.000 L3.333,7.000 Z">
                  </path>
                </svg>
              </div>
              <h4>Filter Jobs</h4>
            </div>
          </div>
        </div> 
        <div class="job-category-listing mb-50">
            
          <div class="single-listing">
            <div class="small-section-tittle2">
              <h4>Job Location</h4>
            </div> 
            <div class="select-job-items2">
              <select name="select">
                <option value="">Anywhere</option>
                <option value="">Category 1</option>
                <option value="">Category 2</option>
                <option value="">Category 3</option>
                <option value="">Category 4</option>
              </select>

            </div> 
            <div class="select-Categories pt-80 pb-50">
              <div class="small-section-tittle2">
                <h4>Experience</h4>
              </div>

              <div class="form-check">
                <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
                <label class="form-check-label" for="flexCheckDefault">
                  1-2 Years
                </label>
              </div>
              <div class="form-check">
                <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
                <label class="form-check-label" for="flexCheckDefault">
                  2-3 Years
                </label>
              </div>
              <div class="form-check">
                <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
                <label class="form-check-label" for="flexCheckDefault">
                  3-6 Years
                </label>
              </div>
              <div class="form-check">
                <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
                <label class="form-check-label" for="flexCheckDefault">
                  6-more..
                </label>
              </div>




            </div> 
          </div>
        

        </div>
      </div>
      <div class="col-xl-9 col-lg-9 col-md-8">
        <section class="featured-job-area">
          <div class="container">
            <div class="row">
              <div class="col-lg-12">
                <div class="count-job mb-35">
                  <span>39 Jobs found</span>
                  <div class="select-job-items">
                    <span>Sort by</span>
                    <select name="select">
                      <option value="">None</option>
                      <option value="">job list</option>
                      <option value="">job list</option>
                      <option value="">job list</option>
                    </select>

                  </div>
                </div>
              </div>
            </div>
            <div class="row">

              <style>
                /*Employer grid*/
                .employer-grid {
                  border: 10px;
                  border: 1px solid #eee;
                  box-shadow: 0px 0px 25px #1f1e861f;
                  position: relative;
                  padding: 25px 20px;
                  border-radius: 10px;
                  display: flex;
                  justify-content: space-between;
                  align-items: center;
                  width: 100%;
                }

                .media {
                  width: 90px;
                  height: 90px;
                  line-height: 90px;
                  display: inline-block;
                  text-align: center;
                  border-radius: 10px;
                  box-shadow: 0px 0px 40px #1f1e861f;
                  margin-right: 40px;
                  position: absolute;
                  top: -20px;
                  overflow: hidden;
                }

                .media img {
                  display: block;
                  border-radius: 10px;
                  border-style: none;
                  height: auto;
                  max-width: 100%;
                }

                .right-content {
                  text-align: center;
                  width: 100px;
                  position: absolute;
                  right: 10px;
                  top: 10px;
                }

                .jobs-vacancies {
                  font-weight: 500;
                  color: #17171d;
                  margin: 20px 0px 10px 0px;
                  font-size: 14px;
                }

                .right-content .jobs-vacancies span {
                  color: #00aa18;
                  font-size: 18px;
                  font-weight: 600;
                  display: block;
                  text-align: center;
                }

                .mid-content {
                  padding-top: 80px;
                }

                .mid-content h4 {

                  font-size: 18px;
                  font-weight: 500;
                  color: #17171d;
                  outline: 0px none;
                  text-decoration: none;
                }

                .employer-grid p {
                  font-size: 14px;
                }
              </style>
              {% for company in companies %}

              <div class="col-lg-4 col-md-6">
                <div class="employer-grid mb-5">
                  <div class="media">
                    {% if company.image %}
                    <img src="{{ company.image.url }}" alt="#">
                     {% else %} 
                    <img src="{% static '/static/img/user.png'%}" alt="Image" > 
                     {% endif %}
                   
                  </div>
                  <div class="mid-content">
                    <a href="{% url 'user:company_vacancies' company.id %}" class="job-title">
                      <h4>{{ company.company_name }}</h4>
                    </a>
                    <!-- <a href="employer-detail.html" class="job-websites site-text-primary">Accountancy</a> -->
                    <div class="items-link items-link2">
                      <a href="{% url 'user:company_vacancies' company.id %}">Open Jobs</a>
                    </div>
                  </div>
                  <div class="right-content">
                    <div class="jobs-vacancies"><span>{{ company.job_set.count }}</span>Vacancies</div>
                  </div>
                </div>
              </div>
              {% empty %}
              <h3>No companies found.</h3>

              {% endfor %}


            </div>
          </div>

        </section>
  
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/header.html
{% load static %}
<header>
<nav class="navbar navbar-expand-lg bg-body-tertiary text-bg-dark" aria-label="Eleventh navbar example">
  <div class="container">
    <a href="/" class="d-inline-flex link-body-emphasis text-decoration-none">
      <img src="{% static 'img/logo.png' %}">
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample09"
      aria-controls="navbarsExample09" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExample09">
      <ul class="navbar-nav main_navbar me-auto mb-2 mb-lg-0">
        <li><a href="/" class="nav-link px-0">Home</a></li>
        <li><a href="{% url 'user:job_listing' %}"
            class="nav-link px-0 {% if request.path == '/job_listing/' %}active{% endif %}">Find a Job</a></li>

        <li><a href="{% url 'user:employers' %}"
            class="nav-link px-0 {% if request.path == '/employers/' %}active{% endif %}">Employers</a></li>
        <li><a href="{% url 'user:candidates' %}"
            class="nav-link px-0 {% if request.path == '/candidates/' %}active{% endif %}">Candidates</a></li>
        <li><a href="{% url 'user:about' %}"
            class="nav-link  px-0 {% if request.path == '/about/' %}active{% endif %}">About</a></li>

        <li><a href="{% url 'user:contact' %}"
            class="nav-link px-0 {% if request.path == '/contact/' %}active{% endif %}">Contact</a></li>
      </ul>

    </div>
    <div class="col-md-2 text-end  mx-auto">

      {% if user.is_authenticated %}
      <ul class=" nav  justify-content-end">
        <li class="nav-item dropdown">
          <a class="btn btn-outline-light me-2  dropdown-toggle" type="button" href="#" data-bs-toggle="dropdown"
            aria-expanded="false">

            <span class="mdi mdi-account-outline"></span> </a>


          <ul class="dropdown-menu ">

            {% if user.is_authenticated %}
            {% if is_applicant %}
            <li> <a href="{% url 'user:user_homepage' %}"
                class="list-group-item list-group-item-action d-flex gap-3  dropdown-item" aria-current="true"
                style=" padding: 20px;  "> 
                <div class="d-flex gap-2 w-100 justify-content-between">
                  <div>
                    <h6 class="mb-0"> {{user.first_name }} {{user.last_name }} </h6>
                    <p class="mb-0 opacity-75">Its Candidates </p>
                  </div>
                </div>
              </a>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>
            <li>
              <a class="dropdown-item d-flex gap-2 align-items-center" href="{% url 'user:user_profile' %}">
                <span class="mdi mdi-account-outline"></span>
                View Profile
              </a>
            </li>

            {% elif is_company %}
            <li> <a href="{% url 'user:company_homepage' %}"
                class="list-group-item list-group-item-action d-flex gap-3  dropdown-item" aria-current="true"
                style=" padding: 20px;  "> 
                <div class="d-flex gap-2 w-100 justify-content-between">
                  <div>
                    <h6 class="mb-0">{{ user.username }} </h6>
                    <p class="mb-0 opacity-75">Its Company </p>
                  </div>
                </div>
              </a>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>
            <li>
              <a class="dropdown-item d-flex gap-2 align-items-center" href="{% url 'user:company_profile' %}">
                <span class="mdi mdi-account-outline"></span>
                View Profile
              </a>
            </li>

            {% endif %}

            {% endif %}
          
            <li>
               <a class=" me-2 btn " href="{% url 'user:notification' %}">
                 <span class="mdi mdi-bell"></span> Notifications
               </a>
             </li>
            <li>
              <hr class="dropdown-divider">
            </li>
            <li>
              <a class="dropdown-item d-flex gap-2 align-items-center" href="{% url 'user:logout' %}">
                <span class="mdi mdi-logout"></span>
                logout
              </a>
            </li>
          </ul>
        </li>
  
      </ul>
      {% else %}
      <a type="button" href="{% url 'user:login' %}" class="btn btn-outline-light me-2">Login / Sign-up</a>
      {% endif %}
    </div>
  </div>
</nav>
</header>